<?php

/**
 * @file
 * Install, update and uninstall functions for the USAJobs module.
 */

/**
 * Update host url include HTTPS protocol.
 */
function usajobs_update_80201() {
  $config = \Drupal::configFactory()->getEditable('usajobs.settings');
  $config->set('host', 'https://data.usajobs.gov');
  $config->save();
  \Drupal::messenger()->addStatus(t('Updated the host configuration.'));
}

/**
 * Remove host url from configuration.
 */
function usajobs_update_80300() {
  $config = \Drupal::configFactory()->getEditable('usajobs.settings');
  $config->clear('host');
  $config->save();
  \Drupal::messenger()->addStatus(t('Removed the host configuration.'));
}

/**
 * Implements hook_uninstall().
 */
function usajobs_uninstall() {
  $config = \Drupal::configFactory()->getEditable('usajobs.settings');
  $config->delete();
}
