usajobs.settings:
  type: config_object
  label: 'USAJobs Settings'
  mapping:
    host:
      type: string
      label: 'Host'
    user_agent:
      type: email
      label: 'User Agent'
    authorization_key:
      type: string
      label: 'Authorization Key'
    organization_id:
      type: string
      label: 'Organization ID'
